bundler_args: --without development doc
language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - jruby
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
